### ISSUE TITLE
Aumentar tamaño de la caja de respuestas en panel de ticket de usuario y de admin

### ISSUE THREAD

**Issue by fmasystem** [fmasystem/fmasystem#3]
Se debe aumentar a una altura considerable que sea comodo leer varias respuestas, al menos unas 10.

![02b9810f-496b-4891-94f4-95085880ac4b](https://cloud.githubusercontent.com/assets/25758289/22911911/cd5fc266-f238-11e6-8c91-b81fcd3aaffc.jpg)

**Comment by yonkishum** [comment]
posible solución al problema, subiendo el error vía el branch yan-dev

![image](https://cloud.githubusercontent.com/assets/6378461/22940897/d4090952-f2b9-11e6-8aad-d4ae483ab2f6.png)
